workflows:
  flutter-workflow:
    name: Flutter Workdlow
    environment:
      java: 17
    instance_type: macOS_M2
    scripts:
      - flutter pub get
      - flutter clean
      - flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/airsoft.apk
