workflows:
  flutter-workflow:
    name: Flutter Workdlow
    environment:
      java: 11
      flutter: 3.0.0
    instance_type: mac_mini_m2
    scripts:
      - flutter pub get
      - flutter clean
      - flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/airsoft.apk
