workflows:
  flutter-workflow:
    name: Flutter Workdlow
    environment:
      java: 11
      flutter: 3.3.4
    instance_type: mac_mini_m2
    scripts:
      - flutter pub get
      - flutter clean
      - flutter build apk --release --stacktrace
    artifacts:
      - build/app/outputs/flutter-apk/airsoft.apk
